### ISSUE TITLE
Patch Notes Metadata

### ISSUE THREAD

**Issue by george-e-d-g-e** [olta-art/olta-nft-editions#4]
be able to add a patch notes url to each version

**Comment by george-e-d-g-e** [comment]
Correct ☺️

**Comment by george-e-d-g-e** [comment]
@thewhodidthis My thinking is a text file with the patch notes on arweave for each version. So there will be specific patch notes for each version added.

But another solution could be just a single url to a patch notes text file that could contain all the patch notes for every version and be updated whenever that artist wants.

**Comment by thewhodidthis** [comment]
@george-e-d-g-e I like the first option better, wondering which of the two would carry the most fees though, if that could ever be an issue

**Comment by george-e-d-g-e** [comment]
Option 1 definitely carries the most fees but it also maintains a neat history and there for trust
